### ISSUE TITLE
not working with storybook 5.2

### ISSUE THREAD

**Issue by uxnivek** [reg-viz/storycap#127]
dependencies: {
        "@storybook/addon-a11y": "^5.2.0-beta.40",
        "@storybook/addon-actions": "^5.2.0-beta.40",
        "@storybook/addon-info": "^5.2.0-beta.40",
        "@storybook/addon-knobs": "^5.2.0-beta.40",
        "@storybook/addon-options": "^5.2.0-beta.40",
        "@storybook/addon-viewport": "^5.2.0-beta.40",
        "@storybook/cli": "^5.2.0-beta.40",
        "@storybook/react": "^5.2.0-beta.40"
}

when run "storybook-chrome-screenshot -p 9001 -c ./.storybook"

it throws error in console as below

 ERROR  Storybook does not exists. First, let's setup a Storybook!
        See: https://storybook.js.org/basics/quick-start-guide/
 LAUNCH  Launching storybook server ...

 ERROR  An unexpected error occurred, Please make sure message below
spawn C:\Atlas\Features\scope-asb-ui\$(npm bin)\start-storybook ENOENT

(node:5308) UnhandledPromiseRejectionWarning: Error: Browser does not exist
    at Browser.<anonymous> (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:70:27)
    at step (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:32:23)
    at Object.next (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:13:53)
    at C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:3:12)
    at Browser.close (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:67:16)
    at C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\App.js:217:100
    at Array.map (<anonymous>)
    at App.<anonymous> (C:\Atlas\Features\scope-asb-ui\node_modules\storybook-chrome-screenshot\lib\core\app\App.js:217:72)
(node:5308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:5308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Quramy** [comment]
Hi. We've released the next version of this project, formally *Storycap*. Storycap supports Storybook v5.2. Please check it out!
