### ISSUE TITLE
Error: mkdir invalid argument on windows os when stories title contain symbol "|" 

### ISSUE THREAD

**Issue by Vol4n3** [reg-viz/storycap#138]
on system Windows 10 64bit,
node_version 12.14.0
npm_version 6.13.1

i suggest to replace | symbol by underscore for file name.
i try on linux this symbol work
```
Error: EINVAL: invalid argument, mkdir 'D:\Projects\__screenshots__\Foundation|Shapes'
    at Object.mkdirSync (fs.js:823:3)
    at Object.sync (D:\Projects\node_modules\mkdirp\index.js:71:13)
    at D:\Projects\node_modules\storycap\lib\node\file.js:35:20
    at new Promise (<anonymous>)
    at FileSystem.save (D:\Projects\node_modules\storycap\lib\node\file.js:34:16)
    at Object.<anonymous> (D:\Projects\node_modules\storycap\lib\node\screenshot-service.js:46:43)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Projects\node_modules\storycap\lib\node\screenshot-service.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

**Comment by Quramy** [comment]
Thanks for your reporting. I made storycap sanitize unsafe chars and published this fix as v2.3.2.
