### ISSUE TITLE
Can't spawn the start-storybook process

### ISSUE THREAD

**Issue by UsamaHameed** [reg-viz/storycap#142]
Hi, 

I have come accross this issue where I am unable to use the serverCmd flag to start a storybook. Please see the outout below: 
```
> storycap --serverCmd "start-storybook -p 9001" http://localhost:9001/
```
```
info Wait for connecting storybook server http://localhost:9001/.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn start-storybook ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn start-storybook',
  path: 'start-storybook',
  spawnargs: [ '-p', '9001' ]
}
```
Let me know if you need more info. Thank you 😄

**Comment by Quramy** [comment]
Ummm. Pls tell me your environment info(win/mac/linux, Node ver)

**Comment by UsamaHameed** [comment]
Windows 10 running Node v12.13.1

**Comment by Quramy** [comment]
Thx, I think I miss something about child process with cross-env. I’ll investigate 🙇

**Comment by UsamaHameed** [comment]
Let me know if I can help with this if you think it would make a good first OSS issue.

**Comment by Quramy** [comment]
@UsamaHameed 
Sorry for my late reply. I published v2.3.5 with #143 .  I think this issue was caused by missing cp spawning option `{ shell: true }` and I confirmed it fixed via GitHub action's windows-server env.
