### ISSUE TITLE
Using with `@storybook/testing-react` causes error

### ISSUE THREAD

**Issue by kodai3** [reg-viz/storycap#528]
when I use [@storybook/testing-react](https://github.com/storybookjs/testing-react) with `withScreenshot`, It throw error on render.
without `withScreenshot` it pass.

```.preview.js
// .preview.js
import { withScreenshot } from 'storycap';

export const decorators = [withScreenshot];
```

```Button.stories.tsx
// Button.stories.tsx
import { Button, ButtonProps } from '.';

export default {
  component: Button,
} as ComponentMeta<typeof Button>;

export const Primary: StoryObj<ButtonProps> = { args: { variant: 'primary', children: 'ボタン' } };
```

```Button.test.tsx
// Button.test.tsx
import { composeStories } from '@storybook/testing-react';
import { render, screen } from '@testing-library/react';
import * as stories from './Button.stories';

describe('Button', () => {
  const { Primary } = composeStories(stories);

  test('clickable', async () => {
    const onClickSpy = jest.fn();
    render(<Primary {...Primary.args} onClick={onClickSpy} />);
    const buttonElement = screen.getByText('ボタン');

    expect(buttonElement).not.toBeNull();
    buttonElement.click();
    expect(onClickSpy).toHaveBeenCalled();
  });
});
```

<details>
<summary>error content</summary>

```
 8 |   test('Primary Button がclickできる', async () => {
       9 |     const onClickSpy = jest.fn();
    > 10 |     render(<Primary {...Primary.args} onClick={onClickSpy} />);
         |     ^
      11 |     const buttonElement = screen.getByText('ボタン');
      12 |
      13 |     expect(buttonElement).not.toBeNull();

      at url2StoryKey (../../node_modules/storycap/lib/client/trigger-screenshot.js:78:11)
      at stock (../../node_modules/storycap/lib/client/trigger-screenshot.js:131:20)
      at Object.triggerScreenshot (../../node_modules/storycap/lib/client/trigger-screenshot.js:203:5)
      at wrapper (../../node_modules/storycap/lib/client/with-screenshot.js:17:34)
      at ../../node_modules/@storybook/addons/dist/cjs/make-decorator.js:31:14
      at ../../node_modules/@storybook/addons/dist/cjs/make-decorator.js:45:26
      at ../../node_modules/@storybook/store/dist/cjs/decorators.js:28:12
      at decorated (../../node_modules/@storybook/store/dist/cjs/decorators.js:87:12)
      at composedStory (../../node_modules/@storybook/testing-react/src/index.ts:143:12)
      at renderWithHooks (../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (../../node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (../../node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (../../node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (../../node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (../../node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (../../node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (../../node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (../../node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at ../../node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (../../node_modules/@testing-library/react/dist/pure.js:97:26)
      at Object.<anonymous> (src/components/Button/Button.test.tsx:10:5)
      at TestScheduler.scheduleTests (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../../../../../.npm/_npx/cd53aabf71f3f793/node_modules/@jest/core/build/runJest.js:404:19)
```
</details>

**Comment by Quramy** [comment]
Thanks for your reporting this issue and sorry for my late reply.
I fixed this and released patch as v3.1.2.
