### ISSUE TITLE
 Error: failed to find element matching selector inside CapturingBrowser.resetIfTouched()

### ISSUE THREAD

**Issue by stefanroeck** [reg-viz/storycap#806]
The problem as described in #712 still happens. Looking at the source code, the root cause seems to be that the story is re-rendered *before* the cleanup events are fired. 
A fix locally working for me is to move down [the line](https://github.com/nodaguti/storycap/blob/772aa9b677a76c96064467d24db5eeb4317691b0/packages/storycap/src/node/capturing-browser.ts#L127)
```JavaScript
this.setCurrentStory(story, { forceRerender: true })
```

 *after* the cleanup events are fired.

If you agree I can prepare a PR.

Stacktrace of the error:
```
Error: Error: failed to find element matching selector "[data-testid='single-row-actions-button']"
    at ElementHandle.$eval (\visreg-test\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:649:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CapturingBrowser.resetIfTouched (\visreg-test\node_modules\storycap\lib\node\capturing-browser.js:89:13)
    at async CapturingBrowser.screenshot (\visreg-test\node_modules\storycap\lib\node\capturing-browser.js:359:13)
    at async time (\visreg-test\node_modules\storycrawler\lib\timer.js:14:20)
    at async \visreg-test\node_modules\storycap\lib\node\screenshot-service.js:27:39
    at async \visreg-test\node_modules\storycrawler\lib\async-utils.js:153:28
```

**Comment by stefanroeck** [comment]
@Quramy thanks for merging, I'm closing this ticket now. Do you have an ETA for a release already?
